framework:
    rate_limiter:
        username_ip_login:
            policy: 'fixed_window'
            limit: 5
            interval: '1 minutes'
            cache_pool: 'login_throttling.cache'
        ip_login:
            policy: 'fixed_window'
            limit: 25
            interval: '1 minutes'
            cache_pool: 'login_throttling.cache'

    cache:
        pools:
            login_throttling.cache:
                adapter: cache.adapter.filesystem