<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260811120529 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE label (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, color VARCHAR(20) NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA750E8E7EC5785 ON label (board_id)');
        $this->addSql('CREATE TABLE task_label (task_id INT NOT NULL, label_id INT NOT NULL, PRIMARY KEY (task_id, label_id))');
        $this->addSql('CREATE INDEX IDX_C9034BC88DB60186 ON task_label (task_id)');
        $this->addSql('CREATE INDEX IDX_C9034BC833B92F39 ON task_label (label_id)');
        $this->addSql('ALTER TABLE label ADD CONSTRAINT FK_EA750E8E7EC5785 FOREIGN KEY (board_id) REFERENCES board (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_label ADD CONSTRAINT FK_C9034BC88DB60186 FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE task_label ADD CONSTRAINT FK_C9034BC833B92F39 FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification ALTER is_deleted DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE label DROP CONSTRAINT FK_EA750E8E7EC5785');
        $this->addSql('ALTER TABLE task_label DROP CONSTRAINT FK_C9034BC88DB60186');
        $this->addSql('ALTER TABLE task_label DROP CONSTRAINT FK_C9034BC833B92F39');
        $this->addSql('DROP TABLE label');
        $this->addSql('DROP TABLE task_label');
        $this->addSql('ALTER TABLE notification ALTER is_deleted SET DEFAULT false');
    }
}
