<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260814084658 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE checklist_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content VARCHAR(500) NOT NULL, is_completed BOOLEAN NOT NULL, position INT NOT NULL, task_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_99EB20F98DB60186 ON checklist_item (task_id)');
        $this->addSql('ALTER TABLE checklist_item ADD CONSTRAINT FK_99EB20F98DB60186 FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE checklist_item DROP CONSTRAINT FK_99EB20F98DB60186');
        $this->addSql('DROP TABLE checklist_item');
    }
}
